const cfg = require("./config.js")

const strings = {
    tr: {
        "navbar.index": "Ana sayfa",
        "navbar.bots": "Botlar",
        "navbar.codes": "Kodlar",
        "navbar.staffs": "Yetkililer",
        "navbar.sponsors": "Sponsorlar",
        "navbar.partners": "Partnerler",
        "navbar.premium": "Premium",
        "navbar.tags": "Etiketler",
        "navbar.login": "Giriş Yap",
        "navbar.user.profile": "Profil",
        "navbar.user.addbot": "Bot Ekle",
        "navbar.user.addcode": "Kod Ekle",
        "navbar.user.staff": "Yetkili Paneli",
        "navbar.user.logout": "Çıkış Yap",

        "index.section": "Hoş geldin! Burada sunucun için en iyi olabileceğini düşündüğün botları bulabilirsin. Sağ üstteki \"Botlar\" sekmesine giderek bütün botları oradakı arama kısmıyla daha kolay bulabilirsin.",
        "index.new_added": "Yeni Eklenen Botlar",
        "index.certified": "Sertifikalı Botlar",
        "index.new_added_codes": "Yeni Eklenen Kodlar",

        "card.view": "Görüntüle",
        "card.invite": "Ekle",
        "card.edit": "Düzenle",

        "joinDiscord": "Discord'a Katıl",

        "profile.edit.biography": "Biyografi",
        "profile.level": "Seviye",
        "profile.bots": "Botları",
        "profile.codes": "Kodları",
        "profile.botVotes": "Botlarının Oyları",
        "profile.noDesc": "Bir açıklama girilmemiş.",

        "staffs.text": "Site Yetkilileri",
        "staffs.siteadmin": "Site Sahibi",
        "staffs.sitestaff": "Site Yetkilisi",

        "sponsors.text": "Sponsorlar",

        "premium.text": "Premium",

        "partners.text": "Partnerler",

        "bots.section": "Bütün botlar burada yer alır.",

        "codes.section": "Bütün kodlar burada yer alır.",

        "tags.section": "Burada tıkladığınız etikette olan botlar gözükür.",

        "categories.section": "Burada tıkladığınız kategoride olan kodlar gözükür.",

        "botPlaceholder": "Bot ara...",
        "codePlaceholder": "Kod ara...",

        "addbot.labels.prefix": "Ön ek",
        "addbot.labels.support": "Destek Sunucusu",
        "addbot.labels.longDesc": "Uzun Açıklama (HTML, Markdown destekler)",
        "addbot.labels.library": "Kütüphane",
        "addbot.labels.shortDesc": "Kısa Açıklama",
        "addbot.labels.developers": "Diğer Geliştiriciler",
        "addbot.labels.tags": "Etiketler",

        "bot.tags": {
            "Eğlence": "Fun",
            "Müzik": "Music",
            "Yönetim": "Management",
            "Moderasyon": "Moderation",
            "Anime": "Anime",
            "Rol Yapma": "RPG",
            "NSFW": "NSFW",
        },

        "error": "Bir hata oluştu! 1 dakika içinde tekrar dene.",
        "addbot.messages.insufficient": "Doldurmadığın/eksik doldurduğun gerekli bilgiler var.",
        "addbot.messages.tags": "6'dan fazla etiket girdin.",
        "addbot.messages.theresBot": "Bu ID'de bir bot var.",
        "addbot.messages.notbot": "Bu ID'ye sahip kullanıcı bir bot değil.",
        "addbot.messages.newaccount": "Hesabın 2 aydan yeni olduğu için bot ekleyemzsin.",
        "addbot.messages.cantadd": "Şu an siteye bot eklemek kapatılmıştır.",
        "addbot.messages.punished": "Bot ekleme iznin yok.",
        "addbot.messages.maxBot": "Maksimum bot ekleme sınırına ulaştın.",
        "addbot.messages.notInDiscord": "Bot eklemek için Discord sunucumuza katılmalısın. Discord: "+cfg.discordServerURL,
        "editbot.messages.success": "Botun düzenlendi.",
        "addbot.messages.success": "Artık botun onay aşamasında.",

        "addcode.labels.name": "Kod İsmi",
        "addcode.labels.code": "Kod",
        "addcode.labels.library": "Kütüphane",
        "addcode.labels.desc": "Açıklama",
        "addcode.labels.tags": "Etiketler",
        "addcode.messages.theresCode": "Bu isimde bir kod var.",
        "addcode.messages.insufficient": "Doldurmadığın/eksik doldurduğun gerekli bilgiler var.",
        "addcode.messages.tags": "6'dan fazla kategori girdin.",
        "addcode.messages.cantadd": "Şu an siteye kod eklemek kapatılmıştır.",
        "addcode.messages.punished": "Kod ekleme iznin yok.",
        "addcode.messages.notInDiscord": "Kod eklemek için Discord sunucumuza katılmalısın. Discord: "+cfg.discordServerURL,
        "editcode.messages.success": "Kodun düzenlendi.",
        "addcode.messages.success": "Artık kodun onay aşamasında.",

        "apidocs.head": "API Dökümantasyonu",
        "apidocs.text": `Bu modül ile birlikte botunuzun sunucu sayısını https://${cfg.siteURL}/bot/<bot'unun idsi> sayfasına yollayabilirsin. Ayrıca, botuna kullanıcıların oy verip vermediğini sorgulayabilirsin.
        
Örnek kullanım:`,
        "apidocs.usage": `const botlist_api = require("anka-botlist-api");
const api = new botlist_api("<botunun api key'i>")
        
/* discord bot kodları */
        
client.on("ready", async() => {
    const hasVoted = await api.hasVoted("<user>")
    console.log(hasVoted)
    /* eğer kullanıcı oy verdiyse size true değerini verir, vermediyse false değerini verir */
    await api.postGuilds(client.guilds)
    /* işlem başarılı olduğunda konsola bir mesaj atar. */
})`,

        "saved": "Kaydedildi",
        "send": "Gönder",

        "bot.remove.error": "Botu silmek için bu botun sahibi olmalısın.",
        "bot.remove.success": "Bot silindi.",
        "bot.page.apikey.createdRefresh": "Botunuzun API KEY'i oluşturuldu. Sayfayı yenileyin ve tekrar tıklayın.",
        "bot.page.apikey.copied": "Botunuzun API KEY'i kopyalandı.",
        "bot.page.prefix": "Ön Ek",
        "bot.page.servers": "Sunucular",
        "bot.page.library": "Kütüphane",
        "bot.page.votes": "Oylar",
        "bot.page.developers": "Bot Sahipleri",
        "bot.page.tags": "Etiketler",
        "bot.page.support": "Destek Sunucusu",
        "bot.page.invite": "Ekle",
        "bot.page.edit": "Düzenle",
        "bot.page.delete": "Sil",
        "bot.page.vote": "Oy Ver",

        "code.remove.error": "Kodu silmek için bu kodun sahibi ya da kod yetkilisi olmalısın.",
        "code.remove.success": "Kod silindi.",
        "code.copied": "Kod panoya kopyalandı",
        "code.page.library": "Kütüphane",
        "code.page.views": "Görüntülenme",
        "code.page.developer": "Kod Yapımcısı",
        "code.page.categories": "Kategoriler",
        "code.page.copy": "Kopyala",
        "code.page.commandsFolder": "Komutlar Dosyası",
        "code.page.edit": "Düzenle",
        "code.page.delete": "Sil",
        "code.page.mainCode": "Ana Kod (bot.js)",

        "bot.vote.vote": "Oy Ver",
        "bot.vote.section": "Aşağıdaki butona tıklayarak bu bota oy verirsin. Oy verdikten sonra bu bota tekrar oy vermek için 12 saat beklemelisin.",
        "bot.vote.messages.alreadyVoted": "Zaten bu bota oy verdin.",
        "bot.vote.messages.voted": "Başarıyla bu bota oy verdin.",
        "bot.vote.messages.error": "Bir hata oluştu.",
        "bot.vote.messages.login": "Giriş yapmalısın.",

        "copied": "Panoya kopyalandı.",
        "footer.language": "Dil",
        "footer.socialMedia": "sosyal Medya",
        "footer.pages": "Sayfalar",
        "footer.siteInfo": "Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama. Site hakkında açıklama.",

        "staff.advertisements.head": "Reklamlar",
        "staff.advertisements.addAd": "Reklam Ekle",
        "staff.advertisements.selectPos": "Yer Seç",
        "staff.advertisements.adImage": "Reklam Resmi",
        "staff.advertisements.fillEverything": "Bütün alanları eksiksiz doldurmalısınız.",
        "staff.advertisements.added": "Reklam eklendi.",
        "staff.advertisements.pos": "Reklamın Yeri",
        "staff.advertisements.image": "Reklamın Resmi",
        "staff.advertisements.acts": "İşlemler",
        "staff.advertisements.delete": "Sil",
        "staff.advertisements.deleted": "Silindi",

        "staff.punishment.head": "Cezalandırma",
        "staff.punishment.toBePunished": "Cezalandırılacak ID",
        "staff.punishment.reason": "Sebep",
        "staff.punishment.punish": "Cezalandır",
        "staff.punishment.selectPunish": "Ceza Seç",
        "staff.punishment.punishments.botBan": "Bot Ekleme Yasağı",
        "staff.punishment.punishments.codeBan": "Kod Ekleme Yasağı",
        "staff.punishment.punishments.siteBan": "Siteye Giriş Yasağı",
        "staff.punishment.fillEverything": "Bütün alanları eksiksiz doldurmalısınız.",
        "staff.punishment.alreadyBanned": "Bu ID zaten cezalı.",
        "staff.punishment.added": "ID cezalandırıldı.",
        "staff.punishment.pos": "ID",
        "staff.punishment.image": "Ceza",
        "staff.punishment.acts": "İşlemler",
        "staff.punishment.delete": "Kaldır",
        "staff.punishment.deleted": "Ceza kaldırıldı.",

        "staff.botquota.head": "Bot Ekleme Kotası",
        "staff.botquota.addQuota": "Bot Rol Ekle",
        "staff.botquota.selectRole": "Rol Seç",
        "staff.botquota.botNumber": "Ekleyeceği bot sayısı",
        "staff.botquota.fillEverything": "Bütün alanları eksiksiz doldurmalısınız.",
        "staff.botquota.alreadyAdded": "Bu rol zaten eklenmiş.",
        "staff.botquota.added": "Bot kotası eklendi.",
        "staff.botquota.role": "Rol İsmi",
        "staff.botquota.number": "Ekleyeceği bot sayısı",
        "staff.botquota.acts": "İşlemler",
        "staff.botquota.delete": "Sil",
        "staff.botquota.deleted": "Silindi",
        "staff.botquota.deletedRole": "silinmiş-rol",

        "staff.bots.head": "Botlar",
        "staff.bots.name": "İsim",
        "staff.bots.owner": "Bot Sahibi",
        "staff.bots.acts": "İşlemler",
        "staff.bots.view": "Görüntüle",
        "staff.bots.delete": "Sil",
        "staff.bots.kick": "At",
        "staff.bots.ban": "Yasakla",
        "staff.bots.certificate.given": "Sertifika verildi",
        "staff.bots.certificate.taken": "Sertifika alındı",
        "staff.bots.specialURL.given": "Özel URL verildi",
        "staff.bots.specialURL.taken": "Özel URL alındı",
        "staff.bots.giveCertificate": "Sertifika Ver",
        "staff.bots.takeCertificate": "Sertifikayı Al",
        "staff.bots.giveSpecialURL": "Özel URL Ver",
        "staff.bots.takeSpecialURL": "Özel URL'yi AL",
        "staff.bots.deleted": "Bot silindi.",
        "staff.bots.kicked": "Bot atıldı ve sistemden silindi.",
        "staff.bots.banned": "Bot yasaklandı ve sistemden silindi.",

        "staff.certifiedbots.head": "Sertifikalı Botlar",
        "staff.certifiedbots.name": "İsim",
        "staff.certifiedbots.owner": "Bot Sahibi",
        "staff.certifiedbots.acts": "İşlemler",
        "staff.certifiedbots.view": "Görüntüle",
        "staff.certifiedbots.delete": "Sil",
        "staff.certifiedbots.kick": "At",
        "staff.certifiedbots.ban": "Yasakla",
        "staff.certifiedbots.certificate.given": "Sertifika verildi",
        "staff.certifiedbots.certificate.taken": "Sertifika alındı",
        "staff.certifiedbots.specialURL.given": "Özel URL verildi",
        "staff.certifiedbots.specialURL.taken": "Özel URL alındı",
        "staff.certifiedbots.giveCertificate": "Sertifika Ver",
        "staff.certifiedbots.takeCertificate": "Sertifikayı Al",
        "staff.certifiedbots.giveSpecialURL": "Özel URL Ver",
        "staff.certifiedbots.takeSpecialURL": "Özel URL'yi AL",
        "staff.certifiedbots.deleted": "Bot silindi.",
        "staff.certifiedbots.kicked": "Bot atıldı ve sistemden silindi.",
        "staff.certifiedbots.banned": "Bot yasaklandı ve sistemden silindi.",

        "staff.index.cards.staffs": "Yetkililer",
        "staff.index.cards.bannedBots": "Yasaklı Botlar",
        "staff.index.cards.kickedBots": "Atılmış Botlar",
        "staff.index.cards.bots": "Botlar",
        "staff.index.cards.approvedbots": "Onaylı Botlar",
        "staff.index.cards.waitingbots": "Bekleyen Botlar",
        "staff.index.cards.certifiedbots": "Sertifikalı Botlar",

        "staff.levelroles.head": "Seviye Rolleri",
        "staff.levelroles.addLevelRole": "Bot Rol Ekle",
        "staff.levelroles.selectRole": "Rol Seç",
        "staff.levelroles.roleImage": "Rol Rozet Resmi",
        "staff.levelroles.fillEverything": "Bütün alanları eksiksiz doldurmalısınız.",
        "staff.levelroles.alreadyAdded": "Bu rol zaten eklenmiş.",
        "staff.levelroles.added": "Seviye rozeti eklendi.",
        "staff.levelroles.role": "Rol İsmi",
        "staff.levelroles.roleBadge": "Rozet Resmi Linki",
        "staff.levelroles.acts": "İşlemler",
        "staff.levelroles.delete": "Sil",
        "staff.levelroles.deleted": "Silindi",
        "staff.levelroles.deletedRole": "silinmiş-rol",

        "staff.codesettings.head": "Code List Ayarları",
        "staff.codesettings.addCodeStaff": "Kod Yetkilisi Rolü Ekle",
        "staff.codesettings.addCodePublisher": "Kod Paylaşımcısı Rolü Ekle",
        "staff.codesettings.addCategoryRole": "Kategori Rolü Ekle",
        "staff.codesettings.addCodeCategories": "Kod Kategorisi Ekle",
        "staff.codesettings.selectRole": "Rol Seç",
        "staff.codesettings.writeCategoryName": "Kategori İsmi Yaz",
        "staff.codesettings.fillEverything": "Bütün alanları eksiksiz doldurmalısınız.",
        "staff.codesettings.alreadyAddedRole": "Bu rol zaten eklenmiş.",
        "staff.codesettings.alreadyAddedCategory": "Bu kategori zaten eklenmiş",
        "staff.codesettings.addedRole": "Kod yetkilisi rolü eklendi.",
        "staff.codesettings.addedRolePublisher": "Kod paylaşımcısı rolü eklendi.",
        "staff.codesettings.addedCategoryRole": "Kategorü rolü eklendi.",
        "staff.codesettings.addedCategory": "Kategori eklendi.",
        "staff.codesettings.role": "Rol İsmi",
        "staff.codesettings.category": "Kategori İsmi",
        "staff.codesettings.acts": "İşlemler",
        "staff.codesettings.delete": "Sil",
        "staff.codesettings.deleted": "Silindi",
        "staff.codesettings.deletedRole": "silinmiş-rol",

        "staff.pendingbots.head": "Beklemedeki Botlar",
        "staff.pendingbots.name": "İsim",
        "staff.pendingbots.owner": "Bot Sahibi",
        "staff.pendingbots.acts": "İşlemler",
        "staff.pendingbots.view": "Görüntüle",
        "staff.pendingbots.delete": "Reddet",
        "staff.pendingbots.inviteToTestServer": "Test Sunucusuna Ekle",
        "staff.pendingbots.inviteToMainServer": "Ana Sunucuya Ekle",
        "staff.pendingbots.youDontHavePermission": "Bunu yapmak için yetkin yok.",
        "staff.pendingbots.deleted": "Bot reddedildi.",
        "staff.pendingbots.approved": "Bot onaylandı.",
        "staff.pendingbots.approve": "Onayla",
        "staff.pending.bots.regularly": "Düzenli bot onaylama sistemi devrede olduğu için öncelikle ilk sıradaki botu kontrol etmelisin.",

        "staff.waitingcodes.head": "Beklemedeki Kodlar",
        "staff.waitingcodes.name": "İsim",
        "staff.waitingcodes.owner": "Kod Yapımcısı",
        "staff.waitingcodes.acts": "İşlemler",
        "staff.waitingcodes.view": "Görüntüle",
        "staff.waitingcodes.delete": "Reddet",
        "staff.waitingcodes.youDontHavePermission": "Bunu yapmak için yetkin yok.",
        "staff.waitingcodes.deleted": "Kod reddedildi.",
        "staff.waitingcodes.approved": "Kod onaylandı.",
        "staff.waitingcodes.approve": "Onayla",
        "staff.waitingcodes.regularly": "Düzenli kod onaylama sistemi devrede olduğu için öncelikle ilk sıradaki kodu kontrol etmelisin.",

        "staff.approvedcodes.head": "Kodlar",
        "staff.approvedcodes.name": "İsim",
        "staff.approvedcodes.owner": "Kod Yapımcısı",
        "staff.approvedcodes.acts": "İşlemler",
        "staff.approvedcodes.youDontHavePermission": "Bunu yapmak için yetkin yok.",
        "staff.approvedcodes.view": "Görüntüle",
        "staff.approvedcodes.delete": "Sil",
        "staff.approvedcodes.deleted": "Kod silindi.",


        "staff.settings.head": "Ayarlar",
        "staff.settings.botApp": "Bot Başvurusu Kapalı/Açık",
        "staff.settings.regularlyBotControl": "Düzenli Bot Onaylama Kapalı/Açık",
        "staff.settings.codeApp": "Kod Başvurusu Kapalı/Açık",
        "staff.settings.regularlyCodeControl": "Düzenli Kod Onaylama Kapalı/Açık",

        "staff.index.stats.staff.totalCodes": "Yetkili Kod İstatistikleri",
        "staff.index.stats.user.totalCodes": "Kullanıcı Kod İstatistikleri",
        "staff.index.stats.selectCategory": "Kategori Seç",
        "staff.index.stats.totalCodes.table.id": "ID",
        "staff.index.stats.totalCodes.table.tag": "Kullanıcı Tag",
        "staff.index.stats.totalCodes.table.totalCodes": "Eklediği Toplam Kodlar",

        "staff.index.stats.staff.totalBots": "Yetkili Bot İstatistikleri",
        "staff.index.stats.totalBots.table.id": "ID",
        "staff.index.stats.totalBots.table.tag": "Kullanıcı Tag",
        "staff.index.stats.totalBots.table.totalBots": "Onayladığı Toplam Botlar",

        "staff.sidebar.head": "Yetkili Paneli",
        "staff.sidebar.punishments": "Cezalandırmalar",
        "staff.sidebar.home": "Ana sayfa",
        "staff.sidebar.approvedBots": "Onaylanan Botlar",
        "staff.sidebar.ads": "Reklamlar",
        "staff.sidebar.levelRoles": "Seviye Rolleri",
        
        "staff.sidebar.codeSettings": "Code List Ayarları",
        "staff.sidebar.certifiedBots": "Sertifikalı Botlar",
        "staff.sidebar.waitingBots": "Beklemedeki Botlar",
        "staff.sidebar.settings": "Ayarlar",
        "staff.sidebar.addBotQuota": "Bot Ekleme Kotası",
        "staff.sidebar.back": "Siteye Dön",

        "staff.sidebar.codeshare": "Kod Paylaşım",
        "staff.sidebar.categories": "Kategoriler",
        "staff.sidebar.waitingCodes": "Bekleyen Kodlar",
        "staff.sidebar.approvedCodes": "Onaylanan Kodlar",
    },
    en: {
        "navbar.index": "Home",
        "navbar.bots": "Bots",
        "navbar.codes": "Codes",
        "navbar.staffs": "Staffs",
        "navbar.sponsors": "Sponsors",
        "navbar.tags": "Tags",
        "navbar.partners": "Partners",
        "navbar.premium": "Premium",
        "navbar.login": "Login",
        "navbar.user.profile": "Profile",
        "navbar.user.addbot": "Add Bot",
        "navbar.user.addcode": "Add Code",
        "navbar.user.staff": "Admin Panel",
        "navbar.user.logout": "Logout",
 
        "index.section": "Welcome! Here you can find bots that you think might be the best for your server. You can find all bots more easily by going to the \"Bots\" tab at the top right with the search section there.",
        "index.new_added": "New Added Bots",
        "index.certified": "Certified Bots",
        "index.new_added_codes": "New Codes",
 
        "card.view": "View",
        "card.invite": "İnvite",
        "card.edit": "Edit",
 
        "joinDiscord": "Join Discord",

        "apidocs.head": "API Documentation",
        "apidocs.text": `With this module, you can post your servers to the https://${cfg.siteURL}/bot/<your bot's id> page. Also, you can fetch voted members to your bot.
        
Example usage:`,
        "apidocs.usage": `const botlist_api = require("anka-botlist-api");
const api = new botlist_api("<your bot's api key>")
        
/* discord bot stuff */
        
client.on("ready", async() => {
    const hasVoted = await api.hasVoted("<user>")
    console.log(hasVoted)
    /* if user voted, it gives you true; if not, it gives false. */
    await api.postGuilds(client.guilds)
    /* it's logging a message to the console when response is successfull. */
})`,
 
        "profile.edit.biography": "Biography",
        "profile.level": "Level",
        "profile.bots": "Bots",
        "profile.codes": "Codes",
        "profile.noDesc": "No description has been entered.",
        "profile.botVotes": "User's Bots' Votes",
 
        "staffs.text": "Site Staffs",
        "staffs.siteadmin": "Site Administrator",
        "staffs.sitestaff": "Site Moderator",
 
        "sponsors.text": "Sponsors",
 
        "premium.text": "Premium",
 
        "partners.text": "Partners",
 
        "bots.section": "All bots are located here.",

        "codes.section": "All codes are located here.",
 
        "tags.section": "Bots with the tag you clicked here will appear.",

        "categories.section": "Codes with the category you clicked here will appear.",
 
        "botPlaceholder": "Search for bots ...",
        "codePlaceholder": "Search for codes ...",
 
        "addbot.labels.prefix": "Prefix",
        "addbot.labels.support": "Support Server",
        "addbot.labels.longDesc": "Long Description (HTML, Markdown supports)",
        "addbot.labels.library": "Library",
        "addbot.labels.shortDesc": "Short Description",
        "addbot.labels.developers": "Other Developers",
        "addbot.labels.tags": "Tags",
 
        "bot.tags": {
            "Fun": "Fun",
            "Music": "Music",
            "Management": "Management",
            "Moderation": "Moderation",
            "Anime": "Anime",
            "RPG": "RPG",
            "NSFW": "NSFW",
        },
 
        "error": "Something went wrong! Try again in 1 minute.",
        "addbot.messages.insufficient": "There is required information that you did not fill in / missing.",
        "addbot.messages.tags": "You have entered more than 6 tags.",
        "addbot.messages.theresBot": "There is a bot with this ID.",
        "addbot.messages.notbot": "The user with this ID is not a bot.",
        "addbot.messages.newaccount": "You cannot add bots as your account is less than 2 months old.",
        "addbot.messages.cantadd": "Adding bots to the site is now closed.",
        "addbot.messages.punished": "You don't have to add bot permission.",
        "addbot.messages.maxBot": "You have reached maximum adding bot capacity.",
        "addbot.messages.notInDiscord": "You have to join our Discord server to add bot. Discord: "+cfg.discordServerURL,
        "editbot.messages.success": "Your bot has been edited.",
        "addbot.messages.success": "The bot is now in the approval stage",

        "addcode.labels.name": "Code Name",
        "addcode.labels.code": "Code",
        "addcode.labels.library": "Library",
        "addcode.labels.desc": "Description",
        "addcode.labels.tags": "Tags",
        "addcode.messages.insufficient": "There is required information that you did not fill in / missing.",
        "addcode.messages.tags": "You have entered more than 6 tags.",
        "addcode.messages.theresCode": "There is a code with this name.",
        "addcode.messages.cantadd": "Adding code to the site is now closed.",
        "addcode.messages.punished": "You don't have to add code permission.",
        "addcode.messages.notInDiscord": "You have to join our Discord server to add code. Discord: "+cfg.discordServerURL,
        "editcode.messages.success": "Your code has been edited.",
        "addcode.messages.success": "The code is now in the approval stage",

        "code.remove.error": "You must be this code's developer or code staff to delete this code.",
        "code.remove.success": "Code has removed.",
        "code.copied": "Code copied to your copyboard.",
        "code.page.library": "Library",
        "code.page.views": "Views",
        "code.page.developer": "Code Developer",
        "code.page.categories": "Categories",
        "code.page.copy": "Copy",
        "code.page.edit": "Edit",
        "code.page.delete": "Delete",
        "code.page.commandsFolder": "Commands Folder",
        "code.page.mainCode": "Main Code (bot.js)",
 
        "saved": "Saved",
        "send": "Send",
 
        "bot.remove.error": "You must be the owner of the bot to delete the bot.",
        "bot.remove.success": "Bot has been deleted.",
        "bot.page.apikey.createdRefresh": "Your bot's API KEY has been created. Please refresh the page and click again.",
        "bot.page.apikey.copied": "Your bot's API KEY has been copied.",
        "bot.page.prefix": "Prefix",
        "bot.page.servers": "Servers",
        "bot.page.library": "Library",
        "bot.page.votes": "Votes",
        "bot.page.developers": "Bot Owners",
        "bot.page.tags": "Tags",
        "bot.page.support": "Support Server",
        "bot.page.invite": "Add",
        "bot.page.edit": "Edit",
        "bot.page.delete": "Delete",
        "bot.page.vote": "Vote",
 
        "bot.vote.vote": "Vote",
        "bot.vote.section": "You vote for this bot by clicking the button below. After voting, you must wait 12 hours before you can vote for this bot again.",
        "bot.vote.messages.alreadyVoted": "You've already voted for this bot.",
        "bot.vote.messages.voted": "You successfully voted for this bot.",
        "bot.vote.messages.error": "Something went wrong.",
        "bot.vote.messages.login": "You must be logged in.",
 
        "copied": "Copied to clipboard.",

        "footer.language": "Language",
        "footer.socialMedia": "Social Media",
        "footer.pages": "Pages",
        "footer.siteInfo": "Description about site. Description about site. Description about site. Description about site. Description about site. Description about site. Description about site. Description about site. Description about site.",

        "staff.advertisements.head": "Ads",
        "staff.advertisements.addAd": "Add Ad",
        "staff.advertisements.selectPos": "Select Location",
        "staff.advertisements.adImage": "Ad Image",
        "staff.advertisements.fillEverything": "You must fill in all fields completely.",
        "staff.advertisements.added": "Ad has been added.",
        "staff.advertisements.pos": "Place of Ad",
        "staff.advertisements.image": "Picture of Ad",
        "staff.advertisements.acts": "Transactions",
        "staff.advertisements.delete": "Delete",
        "staff.advertisements.deleted": "Deleted",

        "staff.punishment.head": "Punishment",
        "staff.punishment.reason": "Reason",
        "staff.punishment.toBePunished": "ID To Be Punished",
        "staff.punishment.punish": "Punish",
        "staff.punishment.selectPunish": "Select a Punish",
        "staff.punishment.punishments.botBan": "Punishing for Adding Bot",
        "staff.punishment.punishments.codeBan": "Punishing for Adding Code",
        "staff.punishment.punishments.siteBan": "Punishing for Logging in to Website",
        "staff.punishment.alreadyBanned": "This ID has already been banned.",
        "staff.punishment.fillEverything": "You must fill in all fields completely.",
        "staff.punishment.added": "ID has been punsihed.",
        "staff.punishment.pos": "ID",
        "staff.punishment.image": "Punish",
        "staff.punishment.acts": "Transactions",
        "staff.punishment.delete": "Delete",
        "staff.punishment.deleted": "Punish deleted.",
 
        "staff.botquota.head": "Bot Adding Quota",
        "staff.botquota.addQuota": "Add Bot Role",
        "staff.botquota.selectRole": "Select Role",
        "staff.botquota.botNumber": "The number of bot it will add",
        "staff.botquota.fillEverything": "You must fill in all fields completely.",
        "staff.botquota.alreadyAdded": "This role has already been added.",
        "staff.botquota.added": "Bot quota has been added.",
        "staff.botquota.role": "Role Name",
        "staff.botquota.number": "The number of bots it will add",
        "staff.botquota.acts": "Transactions",
        "staff.botquota.delete": "Delete",
        "staff.botquota.deleted": "Deleted",
        "staff.botquota.deletedRole": "deleted-role",

        "staff.codesettings.head": "Code List Settings",
        "staff.codesettings.addCodeStaff": "Add Code Staff Role",
        "staff.codesettings.addCodePublisher": "Add Code Publisher Role",
        "staff.codesettings.addCategoryRole": "Add Category Role",
        "staff.codesettings.addCodeCategories": "Add Code Categories",
        "staff.codesettings.selectRole": "Select Role",
        "staff.codesettings.writeCategoryName": "Write category name",
        "staff.codesettings.fillEverything": "You must fill in all fields completely.",
        "staff.codesettings.alreadyAddedRole": "This role has already been added.",
        "staff.codesettings.alreadyAddedCategory": "This category has already been added.",
        "staff.codesettings.addedRole": "Code staff role has been added.",
        "staff.codesettings.addedRolePublisher": "Code publisher role has been added.",
        "staff.codesettings.addedCategoryRole": "Category role has been added.",
        "staff.codesettings.addedCategory": "Category has been added.",
        "staff.codesettings.role": "Role Name",
        "staff.codesettings.category": "Category Name",
        "staff.codesettings.acts": "Transactions",
        "staff.codesettings.delete": "Delete",
        "staff.codesettings.deleted": "Deleted",
        "staff.codesettings.deletedRole": "deleted-role",
 
        "staff.bots.head": "Bots",
        "staff.bots.name": "Name",
        "staff.bots.owner": "Bot Owner",
        "staff.bots.acts": "Transactions",
        "staff.bots.view": "View",
        "staff.bots.delete": "Delete",
        "staff.bots.kick": "Kick",
        "staff.bots.ban": "Ban",
        "staff.bots.certificate.given": "Certificate has been given",
        "staff.bots.certificate.taken": "Certificate has been taken",
        "staff.bots.specialURL.given": "Special URL has been given",
        "staff.bots.specialURL.taken": "Special URL has been taken",
        "staff.bots.giveCertificate": "Give Certificate",
        "staff.bots.takeCertificate": "Take Certificate",
        "staff.bots.giveSpecialURL": "Give Special URL",
        "staff.bots.takeSpecialURL": "Take Special URL",
        "staff.bots.deleted": "Bot has been deleted.",
        "staff.bots.kicked": "Bot was kicked and deleted from the system.",
        "staff.bots.banned": "Bot has been banned and deleted from the system.",
 
        "staff.certifiedbots.head": "Certified Bots",
        "staff.certifiedbots.name": "Name",
        "staff.certifiedbots.owner": "Bot Owner",
        "staff.certifiedbots.acts": "Transactions",
        "staff.certifiedbots.view": "View",
        "staff.certifiedbots.delete": "Delete",
        "staff.certifiedbots.kick": "Kİck",
        "staff.certifiedbots.ban": "Ban",
        "staff.certifiedbots.certificate.given": "Certificate has been given",
        "staff.certifiedbots.certificate.taken": "Certificate has been taken",
        "staff.certifiedbots.specialURL.given": "Special URL has been given",
        "staff.certifiedbots.specialURL.taken": "Special URL has been taken",
        "staff.certifiedbots.giveCertificate": "Give Certificate",
        "staff.certifiedbots.takeCertificate": "Take Certificate",
        "staff.certifiedbots.giveSpecialURL": "Give Special URL",
        "staff.certifiedbots.takeSpecialURL": "Take Special URL",
        "staff.certifiedbots.deleted": "Bot has been deleted.",
        "staff.certifiedbots.kicked": "Bot was kicked and deleted from the system.",
        "staff.certifiedbots.banned": "Bot has been banned and deleted from the system.",

        "staff.index.cards.staffs": "Staffs",
        "staff.index.cards.bannedBots": "Banned Bots",
        "staff.index.cards.kickedBots": "Kicked Bots",
        "staff.index.cards.bots": "Bots",
        "staff.index.cards.approvedbots": "Approved Bots",
        "staff.index.cards.waitingbots": "Waiting Bots",
        "staff.index.cards.certifiedbots": "Certified Bots",

        "staff.index.stats.staff.totalCodes": "Staff Code Stats",
        "staff.index.stats.user.totalCodes": "User Code Stats",
        "staff.index.stats.selectCategory": "Select Category",
        "staff.index.stats.totalCodes.table.id": "ID",
        "staff.index.stats.totalCodes.table.tag": "User Tag",
        "staff.index.stats.totalCodes.table.totalCodes": "Total Added Codes",

        "staff.index.stats.staff.totalBots": "Staff Bot Stats",
        "staff.index.stats.totalBots.table.id": "ID",
        "staff.index.stats.totalBots.table.tag": "User Tag",
        "staff.index.stats.totalBots.table.totalBots": "Total Approved Bots",
 
        "staff.levelroles.head": "Level Roles",
        "staff.levelroles.addLevelRole": "Add Bot Role",
        "staff.levelroles.selectRole": "Select Role",
        "staff.levelroles.roleImage": "Role Badge Image",
        "staff.levelroles.fillEverything": "You must fill in all fields completely.",
        "staff.levelroles.alreadyAdded": "This role has already been added.",
        "staff.levelroles.added": "Level role has been added.",
        "staff.levelroles.role": "Role Name",
        "staff.levelroles.roleBadge": "Role Badge Image",
        "staff.levelroles.acts": "Transactions",
        "staff.levelroles.delete": "Delete",
        "staff.levelroles.deleted": "Deleted",
        "staff.levelroles.deletedRole": "deleted-role",
 
        "staff.pendingbots.head": "Pending Bots",
        "staff.pendingbots.name": "Name",
        "staff.pendingbots.owner": "Bot Owner",
        "staff.pendingbots.acts": "Transactions",
        "staff.pendingbots.view": "View",
        "staff.pendingbots.delete": "Decline",
        "staff.pendingbots.inviteToTestServer": "İnvite To Test Server",
        "staff.pendingbots.inviteToMainServer": "İnvite To Main Server",
        "staff.pendingbots.deleted": "Bot was denied.",
        "staff.pendingbots.approved": "Bot was approved.",
        "staff.pendingbots.approve": "Approve",
        "staff.pending.bots.regularly": "You should check the bot in the first place for the first regular bot confirmation system is activated.",

        "staff.waitingcodes.head": "Waiting Codes",
        "staff.waitingcodes.name": "Name",
        "staff.waitingcodes.owner": "Code Developer",
        "staff.waitingcodes.acts": "Transactions",
        "staff.waitingcodes.view": "View",
        "staff.waitingcodes.youDontHavePermission": "You don't have permission to do this.",
        "staff.waitingcodes.delete": "Decline",
        "staff.waitingcodes.deleted": "Code has denied.",
        "staff.waitingcodes.approved": "Code has approved.",
        "staff.waitingcodes.approve": "Approve",
        "staff.waitingcodes.regularly": "You should check the code in the first place because of the first regular code confirmation system is activated.",

        "staff.approvedcodes.head": "Codes",
        "staff.approvedcodes.name": "Name",
        "staff.approvedcodes.owner": "Code Developer",
        "staff.approvedcodes.youDontHavePermission": "You don't have permission to do this.",
        "staff.approvedcodes.acts": "Transactions",
        "staff.approvedcodes.view": "View",
        "staff.approvedcodes.delete": "Delete",
        "staff.approvedcodes.deleted": "Code has deleted.",

        "staff.settings.head": "Settings",
        "staff.settings.botApp": "Bot Application Disable/Enable",
        "staff.settings.codeApp": "Code Application Disable/Enable",
        "staff.settings.regularlyBotControl": "Regularly Bot Control Disable/Enable",
        "staff.settings.regularlyCodeControl": "Regularly Code Control Disable/Enable",
 
        "staff.sidebar.head": "Admin Panel",
        "staff.sidebar.punishments": "Punishments",
        "staff.sidebar.home": "Home",
        "staff.sidebar.approvedBots": "Approved Bots",
        "staff.sidebar.ads": "Ads",
        "staff.sidebar.levelRoles": "Level Roles",
        "staff.sidebar.certifiedBots": "Certified Bots",
        "staff.sidebar.waitingBots": "Waiting Bots",

        "staff.sidebar.codeSettings": "Code List Settings",

        "staff.sidebar.codeshare": "Code Share",
        "staff.sidebar.categories": "Categories",
        "staff.sidebar.waitingCodes": "Waiting Codes",
        "staff.sidebar.approvedCodes": "Approved Codes",
        
        "staff.sidebar.settings": "Settings",
        "staff.sidebar.addBotQuota": "Bot Adding Quota",
        "staff.sidebar.back": "Return to Site",
    },
}

module.exports = (text, language, ...args) => {
    let string = strings[language];
    if (!string) { string = strings["en"][text] } else { string = strings[language][text] } ;
    return string;
};

module.exports.strings = strings;
module.exports.langs = ["tr", "en"];

module.exports.link = (lang, link, path) => {
    const href = link.replace(/(^\w+:|^)\/\//, '').split("/").slice(1)
    if (path) return "/" + lang + "/" + path
    return "/" + lang + (href.length >= 1 ? `/${href.map((el) => el).join("/")}` : "")
}